blog/blog.web/Controllers/AdminBlogPostController.cs
using blog.web.Models.Domain;
using blog.web.Models.ViewModels;
using blog.web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace blog.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostController : Controller
    {

        private readonly ITagRepository tagRepository;

        private readonly IBlogPostRepository _blogPostRepository;

        public AdminBlogPostController( ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;

            this._blogPostRepository = blogPostRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // get tag for repository
        var tags = await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            //map view model to domain model

            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };



            // map tags from selected tags
            var seletcdTempTagToholdData = new List<Tag>();
            foreach (var selectedTagId in addBlogPostRequest.SeletcedTags)
            {

                var selectedTagIdGuid = Guid.Parse(selectedTagId);

                var exsitingTag = await tagRepository.GetAsync(selectedTagIdGuid);

                if (exsitingTag != null)
                {
                    seletcdTempTagToholdData.Add(exsitingTag);
                }
            }

            // maping tags back to domain model
            blogPost.Tags = seletcdTempTagToholdData;


            await _blogPostRepository.AddAsync(blogPost);



            return RedirectToAction("Add");
        }


        [HttpGet]
        public async Task<IActionResult> List()
        {

            // call repository
           var post =  await _blogPostRepository.GetAllAsync();

            return View(post);
        }



        [HttpGet]
        public async Task< IActionResult> Edit(Guid id) 
        {
            // first we need to reterive data from repository 

           var blogPost = await _blogPostRepository.GetAsync(id);

           // var tags = new LinkedList<Tag>();

            var tagsDomainModel = await tagRepository.GetAllAsync();  


            if (blogPost != null)
            {
                // map domain model into view model 
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),

                    SeletcedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray(),

                };

                return View(model);
            }

           


            return View(null);
        
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            // map view model back to domain model 

            var blogDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                UrlHandle = editBlogPostRequest.UrlHandle,
                ShortDescription = editBlogPostRequest.ShortDescription,
                PublishedDate = editBlogPostRequest.PublishedDate,
                Visible = editBlogPostRequest.Visible,

            };

            // map tags into domain model 

            var selectedTags = new List<Tag>();
            
            foreach(var selectedTag in editBlogPostRequest.SeletcedTags)
            
            { 
            if(Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);


                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            
            }
            
            blogDomainModel.Tags = selectedTags;    

            // submit inforamtion to repository
            var updateBlog = await _blogPostRepository.UpdateAsync(blogDomainModel);

            if (updateBlog != null)
            {
                // show success notification
                return RedirectToAction("Edit");
            }
            // show error notification
            return RedirectToAction("Edit");
        }


        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            // send req to repositor to delete the post
            var deleteBlogPost = await _blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deleteBlogPost != null)
            {
                // show success notif
                return RedirectToAction("List");

            }

            // show error notif

            return RedirectToAction("Edit", new {id = editBlogPostRequest.Id});
        }
    }
}

blog/blog.web/Controllers/AdminTagsController.cs
using blog.web.Data;
using blog.web.Models.Domain;
using blog.web.Models.ViewModels;
using blog.web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace blog.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {


        private readonly ITagRepository tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {

            if (ModelState.IsValid)
            {
                return View();
            }

            // var name = addTagRequest.Name;
            //var displayName = addTagRequest.DisplayName;

            // maping addtagrequest to tag domain model 
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };


           await tagRepository.AddAsync(tag);


            return RedirectToAction("List");
        }


        // read data from db
        [HttpGet]
        [ActionName("List")]
        public async Task< IActionResult> List()
        {

            // use dbcontext to read the tags
           var tags = await tagRepository.GetAllAsync();
            
            return View(tags);
        }

        
        
        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id) 
        {
           
           var  tag = await tagRepository.GetAsync(id);

            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName,
                };
                return View(editTagRequest);
            }

            return View(null); 
        
        }

        [HttpPost]
        public async Task< IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,

            };
       
           var updateTag = await tagRepository.UpdateAsync(tag);

            if (updateTag != null) 
            { 
              // show success messages

            } else
            {
                // show error messges 
            }


            // show error notification
            return RedirectToAction("Edit", new {id = editTagRequest.Id});
        }




        [HttpPost]
        public async Task< IActionResult> Delete(EditTagRequest editTagRequest)
        {
          
           var delete = await tagRepository.DeleteAsync(editTagRequest.Id);

            if (delete != null)
            {
                //show success 
            return RedirectToAction("List");
            }
           
            // show error notification
            return RedirectToAction("Edit" , new {id = editTagRequest.Id});

        }
    }
    
}

blog/blog.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<IdentityUser> signInM;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - blog.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/blog.web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">blog.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (signInM.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">

                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a></li>

                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">Show All Tags</a></li>

                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost" asp-action="Add">Add-Post</a></li>

                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost" asp-action="List">List-Of-Post</a></li>

                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminUsers" asp-action="List">All Users</a></li>
                                </ul>
                            </li>
                        }
                      

                      

                    </ul>


                    <div class="d-flex align-items-center">

                        @if (signInM.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">

                                @User?.Identity?.Name

                            </div>
                            <a class="btn  me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        }
                        else
                        {

                            <a class="btn  me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="btn  me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>

                        }


                       

                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - blog.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>